services:
  mongo:
    image: mongo:latest
    container_name: monogo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  backend:
    build:  ${BACKEND_IMAGE}:${IMAGE_TAG}
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/UserDb
    

  client:
    build: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
    

volumes:
  mongo_data:
