services:
  mongo:
    image: mongo:latest
    container_name: monogo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/UserDb

  client:
    build: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo_data:
